language: cpp
rvm:  
    - 2.0.0
env:
  global:
#    - ARTIFACTS_AWS_REGION=us-east-1
#    - ARTIFACTS_S3_BUCKET=bomberman.ten-forward
#  - secure: "e+lkwagu20aNVU86Rlwf4aJ7nZf1b0WT1s+HHdeWpyqM+O7Zu67z36q1BhgUunv56szVK2xXMU6K2I3KsXemCMO4/KA7usx/HM9uQ65tL6WwuppQYWqPzSiusljas15EpWQsIseNJ2Rjm8lBQY7MP3whurdXtqR8z5N6IxifEMU="
#  - secure: "mhr46ugNFBF/8Vlu8NgPHw5WFV97QzpFzFTOGiaHzp2daYgnAvSKrqmlZ3dCb9fMjPsFFev+XIgybJhpPKSl5yIPu8HvlNPCtyIM8fdAo0Fb00O8dEdWX/ijUTQvLKs9U8dSGPpx98PHzxepSLmEkaUqHtvqCyZE9CA6kPdkq8A="
before_install:
  - git submodule update --init --recursive
before_script:
  - gem install travis-artifacts
script:
  - ln -s thirdparty/cmake/SDL_image.cmake thirdparty/SDL_image/CMakeLists.txt
  - ln -s thirdparty/cmake/SDL_mixer.cmake thirdparty/SDL_mixer/CMakeLists.txt
  - ln -s thirdparty/cmake/SDL_ttf.cmake thirdparty/SDL_ttf/CMakeLists.txt
  - mkdir build-linux
  - cd  build-linux
  - cmake ..
  - make -j 4 all install
#after_success:
#  - if [ $TRAVIS_REPO_SLUG = ssrb/bomberman ] && [ $THE_MAKEFILE = Makefile.android ]; then travis-artifacts upload --path bin/Bomberman-debug.apk; fi
